import type { OpenApiOperationAnalysis } from './api-analysis-service';

export class TestDataService {
  private readonly suffix = `${Date.now()}-${Math.floor(Math.random() * 10000)}`;

  validBody(operation: OpenApiOperationAnalysis): Record<string, unknown> {
    const schemaName = operation.requestSchemaRef?.split('/').pop() ?? '';
    const base: Record<string, Record<string, unknown>> = {
      CreateCountryDto: { name: `Country-${this.suffix}` },
      UpdateCountryDto: { name: `Country-Updated-${this.suffix}` },
      CreateCityDto: { name: `City-${this.suffix}`, countryId: '00000000-0000-0000-0000-000000000001' },
      UpdateCityDto: { name: `City-Updated-${this.suffix}`, countryId: '00000000-0000-0000-0000-000000000001' },
      NewCompanySector: { name: `Sector-${this.suffix}` },
      UpdateCompanySector: { id: '00000000-0000-0000-0000-000000000001', name: `Sector-Updated-${this.suffix}` },
      NewCompanyStatus: { name: `Status-${this.suffix}` },
      UpdateCompanyStatus: { id: '00000000-0000-0000-0000-000000000001', name: `Status-Updated-${this.suffix}` },
      NewActivityLevel: { code: `LEVEL-${this.suffix}`, description: 'Generated by Swagger automation' },
      UpdateActivityLevel: { id: '00000000-0000-0000-0000-000000000001', code: `LEVEL-UPD-${this.suffix}` },
      NewContactSource: { name: `Source-${this.suffix}` },
      UpdateContactSource: { id: '00000000-0000-0000-0000-000000000001', name: `Source-Updated-${this.suffix}` },
      NewActivityType: { name: `Activity-Type-${this.suffix}`, description: 'Generated by Swagger automation' },
      UpdateActivityType: { id: '00000000-0000-0000-0000-000000000001', name: `Activity-Type-Updated-${this.suffix}` },
      NewCompany: { name: `Company-${this.suffix}`, responsible: 'QA Automation' },
      UpdateCompany: { id: '00000000-0000-0000-0000-000000000001', name: `Company-Updated-${this.suffix}`, responsible: 'QA Automation' },
      NewContact: { firstName: `First-${this.suffix}`, lastName: 'Contact', status: 1 },
      UpdateContact: { id: '00000000-0000-0000-0000-000000000001', firstName: `First-Updated-${this.suffix}`, lastName: 'Contact' },
      CreateActivityRequest: { description: 'Generated by Swagger automation' },
      UpdateActivityRequest: { id: '00000000-0000-0000-0000-000000000001', description: 'Updated by Swagger automation' }
    };

    return base[schemaName] ?? {};
  }

  invalidBody(operation: OpenApiOperationAnalysis): Record<string, unknown> {
    const body = this.validBody(operation);
    for (const field of operation.requiredBodyFields) {
      delete body[field];
    }
    return Object.keys(body).length ? body : { invalid: true };
  }

  pathWithInvalidId(path: string) {
    return path.replace('{id}', 'not-a-valid-id');
  }
}
